### ISSUE TITLE
How to use OR in blade

### ISSUE THREAD

**Issue by pishguy** [phpzen/laravel-rbac#2]
hi, how to use `or` in blade?  for example if user is administrator or user is manager ?

```
@ifUserIs('administrator') or ifUserIs('manager')
```

**Comment by pishguy** [comment]
Are you change that in source?

**Comment by phpzen** [comment]
v0.2 is ready. You can use OR operator now.

**Comment by pishguy** [comment]
​Thanks you very much :)

**Comment by pishguy** [comment]
​please update package on composer. i can not update to v.02

**Comment by phpzen** [comment]
Packagist updates tags automatically so change your composer.json:

```
"phpzen/laravel-rbac": "^0.2"
```

and run `composer update`

**Comment by pishguy** [comment]
Oh your are right. i'm sorry i forgot it.
