### ISSUE TITLE
Compatible to Laravel 5.2?

### ISSUE THREAD

**Issue by michaeltansy** [phpzen/laravel-rbac#5]
Hi, is this compatible to Laravel 5.2? I am using laravel 5.2 and Dingo/Api package for Rest Api. Hoping that this package fit in to my existing package.

**Comment by pishguy** [comment]
yes, its compatible with newset version of laravel

**Comment by phpzen** [comment]
Yes it is compatible with Laravel 5.2 and works fine with Dingo/Api
